### ISSUE TITLE
v1.0.0 checklist

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#62]
+ [x] update 0.x dependencies to 1.0.0
  + [x] unipointer
  + [x] unidragger
  + [x] tap-listener
  + [x] fizzy-ui-utils
+ [x] update flickity-imagesloaded to 1.0.0 for 1.0.0
+ [x] update flickity-as-nav-for to 1.0.0 for 1.0.0
+ [x] update `bower.json` with dependency versions
+ [x] update `package.json` with dependency versions
+ [x] Add license to README
+ [x] Add license to `flickity.js` header
+ [x] Add flickity.metafizzy.co to `flickity.css` header
+ [x] `gulp version -t 1.0.0`
+ [x] build dist: `gulp`
+ [x] changelog
+ [x] `git tag -a v1.0.0`
+ [x] `npm publish`
+ [x] add licensing to docs
+ [x] wait till cdnjs updates with `1.0.0`
+ [x] Change cdnjs version `1.0.0`

**Comment by desandro** [comment]
[Flickity v1.0.0 is released](http://flickity.metafizzy.co)!
